// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connect6.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_connect6_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_connect6_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_connect6_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_connect6_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_connect6_2eproto;
namespace connect6 {
class GameState;
struct GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class Move;
struct MoveDefaultTypeInternal;
extern MoveDefaultTypeInternal _Move_default_instance_;
class PlayerAction;
struct PlayerActionDefaultTypeInternal;
extern PlayerActionDefaultTypeInternal _PlayerAction_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
class Row;
struct RowDefaultTypeInternal;
extern RowDefaultTypeInternal _Row_default_instance_;
}  // namespace connect6
PROTOBUF_NAMESPACE_OPEN
template<> ::connect6::GameState* Arena::CreateMaybeMessage<::connect6::GameState>(Arena*);
template<> ::connect6::Move* Arena::CreateMaybeMessage<::connect6::Move>(Arena*);
template<> ::connect6::PlayerAction* Arena::CreateMaybeMessage<::connect6::PlayerAction>(Arena*);
template<> ::connect6::Point* Arena::CreateMaybeMessage<::connect6::Point>(Arena*);
template<> ::connect6::Row* Arena::CreateMaybeMessage<::connect6::Row>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace connect6 {

enum GameState_Status : int {
  GameState_Status_WAITING = 0,
  GameState_Status_PLAYING = 1,
  GameState_Status_FINISHED = 2,
  GameState_Status_GameState_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GameState_Status_GameState_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GameState_Status_IsValid(int value);
constexpr GameState_Status GameState_Status_Status_MIN = GameState_Status_WAITING;
constexpr GameState_Status GameState_Status_Status_MAX = GameState_Status_FINISHED;
constexpr int GameState_Status_Status_ARRAYSIZE = GameState_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameState_Status_descriptor();
template<typename T>
inline const std::string& GameState_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GameState_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GameState_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GameState_Status_descriptor(), enum_t_value);
}
inline bool GameState_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GameState_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GameState_Status>(
    GameState_Status_descriptor(), name, value);
}
enum PlayerColor : int {
  UNKNOWN = 0,
  BLACK = 1,
  WHITE = 2,
  PlayerColor_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerColor_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerColor_IsValid(int value);
constexpr PlayerColor PlayerColor_MIN = UNKNOWN;
constexpr PlayerColor PlayerColor_MAX = WHITE;
constexpr int PlayerColor_ARRAYSIZE = PlayerColor_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerColor_descriptor();
template<typename T>
inline const std::string& PlayerColor_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerColor>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerColor_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerColor_descriptor(), enum_t_value);
}
inline bool PlayerColor_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerColor* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerColor>(
    PlayerColor_descriptor(), name, value);
}
enum GameResult : int {
  ONGOING = 0,
  BLACK_WIN = 1,
  WHITE_WIN = 2,
  DRAW = 3,
  BLACK_TIMEOUT = 4,
  WHITE_TIMEOUT = 5,
  BLACK_INVALID = 6,
  WHITE_INVALID = 7,
  GameResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GameResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GameResult_IsValid(int value);
constexpr GameResult GameResult_MIN = ONGOING;
constexpr GameResult GameResult_MAX = WHITE_INVALID;
constexpr int GameResult_ARRAYSIZE = GameResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameResult_descriptor();
template<typename T>
inline const std::string& GameResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GameResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GameResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GameResult_descriptor(), enum_t_value);
}
inline bool GameResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GameResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GameResult>(
    GameResult_descriptor(), name, value);
}
// ===================================================================

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:connect6.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "connect6.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  int32_t x() const;
  void set_x(int32_t value);
  private:
  int32_t _internal_x() const;
  void _internal_set_x(int32_t value);
  public:

  // int32 y = 2;
  void clear_y();
  int32_t y() const;
  void set_y(int32_t value);
  private:
  int32_t _internal_y() const;
  void _internal_set_y(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:connect6.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t x_;
    int32_t y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connect6_2eproto;
};
// -------------------------------------------------------------------

class PlayerAction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:connect6.PlayerAction) */ {
 public:
  inline PlayerAction() : PlayerAction(nullptr) {}
  ~PlayerAction() override;
  explicit PROTOBUF_CONSTEXPR PlayerAction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerAction(const PlayerAction& from);
  PlayerAction(PlayerAction&& from) noexcept
    : PlayerAction() {
    *this = ::std::move(from);
  }

  inline PlayerAction& operator=(const PlayerAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerAction& operator=(PlayerAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerAction& default_instance() {
    return *internal_default_instance();
  }
  enum ActionCase {
    kRegisterTeam = 1,
    kMove = 2,
    kResign = 3,
    ACTION_NOT_SET = 0,
  };

  static inline const PlayerAction* internal_default_instance() {
    return reinterpret_cast<const PlayerAction*>(
               &_PlayerAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerAction& a, PlayerAction& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerAction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerAction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerAction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerAction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerAction& from) {
    PlayerAction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerAction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "connect6.PlayerAction";
  }
  protected:
  explicit PlayerAction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegisterTeamFieldNumber = 1,
    kMoveFieldNumber = 2,
    kResignFieldNumber = 3,
  };
  // string register_team = 1;
  bool has_register_team() const;
  private:
  bool _internal_has_register_team() const;
  public:
  void clear_register_team();
  const std::string& register_team() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_register_team(ArgT0&& arg0, ArgT... args);
  std::string* mutable_register_team();
  PROTOBUF_NODISCARD std::string* release_register_team();
  void set_allocated_register_team(std::string* register_team);
  private:
  const std::string& _internal_register_team() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_register_team(const std::string& value);
  std::string* _internal_mutable_register_team();
  public:

  // .connect6.Move move = 2;
  bool has_move() const;
  private:
  bool _internal_has_move() const;
  public:
  void clear_move();
  const ::connect6::Move& move() const;
  PROTOBUF_NODISCARD ::connect6::Move* release_move();
  ::connect6::Move* mutable_move();
  void set_allocated_move(::connect6::Move* move);
  private:
  const ::connect6::Move& _internal_move() const;
  ::connect6::Move* _internal_mutable_move();
  public:
  void unsafe_arena_set_allocated_move(
      ::connect6::Move* move);
  ::connect6::Move* unsafe_arena_release_move();

  // bool resign = 3;
  bool has_resign() const;
  private:
  bool _internal_has_resign() const;
  public:
  void clear_resign();
  bool resign() const;
  void set_resign(bool value);
  private:
  bool _internal_resign() const;
  void _internal_set_resign(bool value);
  public:

  void clear_action();
  ActionCase action_case() const;
  // @@protoc_insertion_point(class_scope:connect6.PlayerAction)
 private:
  class _Internal;
  void set_has_register_team();
  void set_has_move();
  void set_has_resign();

  inline bool has_action() const;
  inline void clear_has_action();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ActionUnion {
      constexpr ActionUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr register_team_;
      ::connect6::Move* move_;
      bool resign_;
    } action_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connect6_2eproto;
};
// -------------------------------------------------------------------

class Move final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:connect6.Move) */ {
 public:
  inline Move() : Move(nullptr) {}
  ~Move() override;
  explicit PROTOBUF_CONSTEXPR Move(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Move(const Move& from);
  Move(Move&& from) noexcept
    : Move() {
    *this = ::std::move(from);
  }

  inline Move& operator=(const Move& from) {
    CopyFrom(from);
    return *this;
  }
  inline Move& operator=(Move&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Move& default_instance() {
    return *internal_default_instance();
  }
  static inline const Move* internal_default_instance() {
    return reinterpret_cast<const Move*>(
               &_Move_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Move& a, Move& b) {
    a.Swap(&b);
  }
  inline void Swap(Move* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Move* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Move* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Move>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Move& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Move& from) {
    Move::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Move* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "connect6.Move";
  }
  protected:
  explicit Move(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStonesFieldNumber = 1,
  };
  // repeated .connect6.Point stones = 1;
  int stones_size() const;
  private:
  int _internal_stones_size() const;
  public:
  void clear_stones();
  ::connect6::Point* mutable_stones(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >*
      mutable_stones();
  private:
  const ::connect6::Point& _internal_stones(int index) const;
  ::connect6::Point* _internal_add_stones();
  public:
  const ::connect6::Point& stones(int index) const;
  ::connect6::Point* add_stones();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >&
      stones() const;

  // @@protoc_insertion_point(class_scope:connect6.Move)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point > stones_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connect6_2eproto;
};
// -------------------------------------------------------------------

class Row final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:connect6.Row) */ {
 public:
  inline Row() : Row(nullptr) {}
  ~Row() override;
  explicit PROTOBUF_CONSTEXPR Row(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Row(const Row& from);
  Row(Row&& from) noexcept
    : Row() {
    *this = ::std::move(from);
  }

  inline Row& operator=(const Row& from) {
    CopyFrom(from);
    return *this;
  }
  inline Row& operator=(Row&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Row& default_instance() {
    return *internal_default_instance();
  }
  static inline const Row* internal_default_instance() {
    return reinterpret_cast<const Row*>(
               &_Row_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Row& a, Row& b) {
    a.Swap(&b);
  }
  inline void Swap(Row* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Row* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Row* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Row>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Row& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Row& from) {
    Row::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Row* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "connect6.Row";
  }
  protected:
  explicit Row(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCellsFieldNumber = 1,
  };
  // repeated .connect6.PlayerColor cells = 1;
  int cells_size() const;
  private:
  int _internal_cells_size() const;
  public:
  void clear_cells();
  private:
  ::connect6::PlayerColor _internal_cells(int index) const;
  void _internal_add_cells(::connect6::PlayerColor value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_cells();
  public:
  ::connect6::PlayerColor cells(int index) const;
  void set_cells(int index, ::connect6::PlayerColor value);
  void add_cells(::connect6::PlayerColor value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& cells() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_cells();

  // @@protoc_insertion_point(class_scope:connect6.Row)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> cells_;
    mutable std::atomic<int> _cells_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connect6_2eproto;
};
// -------------------------------------------------------------------

class GameState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:connect6.GameState) */ {
 public:
  inline GameState() : GameState(nullptr) {}
  ~GameState() override;
  explicit PROTOBUF_CONSTEXPR GameState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameState(const GameState& from);
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameState& operator=(GameState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameState& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }
  inline void Swap(GameState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameState& from) {
    GameState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "connect6.GameState";
  }
  protected:
  explicit GameState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GameState_Status Status;
  static constexpr Status WAITING =
    GameState_Status_WAITING;
  static constexpr Status PLAYING =
    GameState_Status_PLAYING;
  static constexpr Status FINISHED =
    GameState_Status_FINISHED;
  static inline bool Status_IsValid(int value) {
    return GameState_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    GameState_Status_Status_MIN;
  static constexpr Status Status_MAX =
    GameState_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    GameState_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return GameState_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return GameState_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return GameState_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kOpponentStonesFieldNumber = 4,
    kBoardFieldNumber = 9,
    kMessageFieldNumber = 6,
    kStatusFieldNumber = 1,
    kIsMyTurnFieldNumber = 2,
    kMyColorFieldNumber = 3,
    kStonesRequiredFieldNumber = 5,
    kWinnerFieldNumber = 7,
    kResultFieldNumber = 8,
  };
  // repeated .connect6.Point opponent_stones = 4;
  int opponent_stones_size() const;
  private:
  int _internal_opponent_stones_size() const;
  public:
  void clear_opponent_stones();
  ::connect6::Point* mutable_opponent_stones(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >*
      mutable_opponent_stones();
  private:
  const ::connect6::Point& _internal_opponent_stones(int index) const;
  ::connect6::Point* _internal_add_opponent_stones();
  public:
  const ::connect6::Point& opponent_stones(int index) const;
  ::connect6::Point* add_opponent_stones();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >&
      opponent_stones() const;

  // repeated .connect6.Row board = 9;
  int board_size() const;
  private:
  int _internal_board_size() const;
  public:
  void clear_board();
  ::connect6::Row* mutable_board(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Row >*
      mutable_board();
  private:
  const ::connect6::Row& _internal_board(int index) const;
  ::connect6::Row* _internal_add_board();
  public:
  const ::connect6::Row& board(int index) const;
  ::connect6::Row* add_board();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Row >&
      board() const;

  // string message = 6;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .connect6.GameState.Status status = 1;
  void clear_status();
  ::connect6::GameState_Status status() const;
  void set_status(::connect6::GameState_Status value);
  private:
  ::connect6::GameState_Status _internal_status() const;
  void _internal_set_status(::connect6::GameState_Status value);
  public:

  // bool is_my_turn = 2;
  void clear_is_my_turn();
  bool is_my_turn() const;
  void set_is_my_turn(bool value);
  private:
  bool _internal_is_my_turn() const;
  void _internal_set_is_my_turn(bool value);
  public:

  // .connect6.PlayerColor my_color = 3;
  void clear_my_color();
  ::connect6::PlayerColor my_color() const;
  void set_my_color(::connect6::PlayerColor value);
  private:
  ::connect6::PlayerColor _internal_my_color() const;
  void _internal_set_my_color(::connect6::PlayerColor value);
  public:

  // int32 stones_required = 5;
  void clear_stones_required();
  int32_t stones_required() const;
  void set_stones_required(int32_t value);
  private:
  int32_t _internal_stones_required() const;
  void _internal_set_stones_required(int32_t value);
  public:

  // .connect6.PlayerColor winner = 7;
  void clear_winner();
  ::connect6::PlayerColor winner() const;
  void set_winner(::connect6::PlayerColor value);
  private:
  ::connect6::PlayerColor _internal_winner() const;
  void _internal_set_winner(::connect6::PlayerColor value);
  public:

  // .connect6.GameResult result = 8;
  void clear_result();
  ::connect6::GameResult result() const;
  void set_result(::connect6::GameResult value);
  private:
  ::connect6::GameResult _internal_result() const;
  void _internal_set_result(::connect6::GameResult value);
  public:

  // @@protoc_insertion_point(class_scope:connect6.GameState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point > opponent_stones_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Row > board_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    int status_;
    bool is_my_turn_;
    int my_color_;
    int32_t stones_required_;
    int winner_;
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connect6_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// int32 x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline int32_t Point::_internal_x() const {
  return _impl_.x_;
}
inline int32_t Point::x() const {
  // @@protoc_insertion_point(field_get:connect6.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(int32_t value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(int32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:connect6.Point.x)
}

// int32 y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline int32_t Point::_internal_y() const {
  return _impl_.y_;
}
inline int32_t Point::y() const {
  // @@protoc_insertion_point(field_get:connect6.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(int32_t value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(int32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:connect6.Point.y)
}

// -------------------------------------------------------------------

// PlayerAction

// string register_team = 1;
inline bool PlayerAction::_internal_has_register_team() const {
  return action_case() == kRegisterTeam;
}
inline bool PlayerAction::has_register_team() const {
  return _internal_has_register_team();
}
inline void PlayerAction::set_has_register_team() {
  _impl_._oneof_case_[0] = kRegisterTeam;
}
inline void PlayerAction::clear_register_team() {
  if (_internal_has_register_team()) {
    _impl_.action_.register_team_.Destroy();
    clear_has_action();
  }
}
inline const std::string& PlayerAction::register_team() const {
  // @@protoc_insertion_point(field_get:connect6.PlayerAction.register_team)
  return _internal_register_team();
}
template <typename ArgT0, typename... ArgT>
inline void PlayerAction::set_register_team(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_register_team()) {
    clear_action();
    set_has_register_team();
    _impl_.action_.register_team_.InitDefault();
  }
  _impl_.action_.register_team_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:connect6.PlayerAction.register_team)
}
inline std::string* PlayerAction::mutable_register_team() {
  std::string* _s = _internal_mutable_register_team();
  // @@protoc_insertion_point(field_mutable:connect6.PlayerAction.register_team)
  return _s;
}
inline const std::string& PlayerAction::_internal_register_team() const {
  if (_internal_has_register_team()) {
    return _impl_.action_.register_team_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void PlayerAction::_internal_set_register_team(const std::string& value) {
  if (!_internal_has_register_team()) {
    clear_action();
    set_has_register_team();
    _impl_.action_.register_team_.InitDefault();
  }
  _impl_.action_.register_team_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerAction::_internal_mutable_register_team() {
  if (!_internal_has_register_team()) {
    clear_action();
    set_has_register_team();
    _impl_.action_.register_team_.InitDefault();
  }
  return _impl_.action_.register_team_.Mutable(      GetArenaForAllocation());
}
inline std::string* PlayerAction::release_register_team() {
  // @@protoc_insertion_point(field_release:connect6.PlayerAction.register_team)
  if (_internal_has_register_team()) {
    clear_has_action();
    return _impl_.action_.register_team_.Release();
  } else {
    return nullptr;
  }
}
inline void PlayerAction::set_allocated_register_team(std::string* register_team) {
  if (has_action()) {
    clear_action();
  }
  if (register_team != nullptr) {
    set_has_register_team();
    _impl_.action_.register_team_.InitAllocated(register_team, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:connect6.PlayerAction.register_team)
}

// .connect6.Move move = 2;
inline bool PlayerAction::_internal_has_move() const {
  return action_case() == kMove;
}
inline bool PlayerAction::has_move() const {
  return _internal_has_move();
}
inline void PlayerAction::set_has_move() {
  _impl_._oneof_case_[0] = kMove;
}
inline void PlayerAction::clear_move() {
  if (_internal_has_move()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.action_.move_;
    }
    clear_has_action();
  }
}
inline ::connect6::Move* PlayerAction::release_move() {
  // @@protoc_insertion_point(field_release:connect6.PlayerAction.move)
  if (_internal_has_move()) {
    clear_has_action();
    ::connect6::Move* temp = _impl_.action_.move_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.action_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::connect6::Move& PlayerAction::_internal_move() const {
  return _internal_has_move()
      ? *_impl_.action_.move_
      : reinterpret_cast< ::connect6::Move&>(::connect6::_Move_default_instance_);
}
inline const ::connect6::Move& PlayerAction::move() const {
  // @@protoc_insertion_point(field_get:connect6.PlayerAction.move)
  return _internal_move();
}
inline ::connect6::Move* PlayerAction::unsafe_arena_release_move() {
  // @@protoc_insertion_point(field_unsafe_arena_release:connect6.PlayerAction.move)
  if (_internal_has_move()) {
    clear_has_action();
    ::connect6::Move* temp = _impl_.action_.move_;
    _impl_.action_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PlayerAction::unsafe_arena_set_allocated_move(::connect6::Move* move) {
  clear_action();
  if (move) {
    set_has_move();
    _impl_.action_.move_ = move;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:connect6.PlayerAction.move)
}
inline ::connect6::Move* PlayerAction::_internal_mutable_move() {
  if (!_internal_has_move()) {
    clear_action();
    set_has_move();
    _impl_.action_.move_ = CreateMaybeMessage< ::connect6::Move >(GetArenaForAllocation());
  }
  return _impl_.action_.move_;
}
inline ::connect6::Move* PlayerAction::mutable_move() {
  ::connect6::Move* _msg = _internal_mutable_move();
  // @@protoc_insertion_point(field_mutable:connect6.PlayerAction.move)
  return _msg;
}

// bool resign = 3;
inline bool PlayerAction::_internal_has_resign() const {
  return action_case() == kResign;
}
inline bool PlayerAction::has_resign() const {
  return _internal_has_resign();
}
inline void PlayerAction::set_has_resign() {
  _impl_._oneof_case_[0] = kResign;
}
inline void PlayerAction::clear_resign() {
  if (_internal_has_resign()) {
    _impl_.action_.resign_ = false;
    clear_has_action();
  }
}
inline bool PlayerAction::_internal_resign() const {
  if (_internal_has_resign()) {
    return _impl_.action_.resign_;
  }
  return false;
}
inline void PlayerAction::_internal_set_resign(bool value) {
  if (!_internal_has_resign()) {
    clear_action();
    set_has_resign();
  }
  _impl_.action_.resign_ = value;
}
inline bool PlayerAction::resign() const {
  // @@protoc_insertion_point(field_get:connect6.PlayerAction.resign)
  return _internal_resign();
}
inline void PlayerAction::set_resign(bool value) {
  _internal_set_resign(value);
  // @@protoc_insertion_point(field_set:connect6.PlayerAction.resign)
}

inline bool PlayerAction::has_action() const {
  return action_case() != ACTION_NOT_SET;
}
inline void PlayerAction::clear_has_action() {
  _impl_._oneof_case_[0] = ACTION_NOT_SET;
}
inline PlayerAction::ActionCase PlayerAction::action_case() const {
  return PlayerAction::ActionCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Move

// repeated .connect6.Point stones = 1;
inline int Move::_internal_stones_size() const {
  return _impl_.stones_.size();
}
inline int Move::stones_size() const {
  return _internal_stones_size();
}
inline void Move::clear_stones() {
  _impl_.stones_.Clear();
}
inline ::connect6::Point* Move::mutable_stones(int index) {
  // @@protoc_insertion_point(field_mutable:connect6.Move.stones)
  return _impl_.stones_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >*
Move::mutable_stones() {
  // @@protoc_insertion_point(field_mutable_list:connect6.Move.stones)
  return &_impl_.stones_;
}
inline const ::connect6::Point& Move::_internal_stones(int index) const {
  return _impl_.stones_.Get(index);
}
inline const ::connect6::Point& Move::stones(int index) const {
  // @@protoc_insertion_point(field_get:connect6.Move.stones)
  return _internal_stones(index);
}
inline ::connect6::Point* Move::_internal_add_stones() {
  return _impl_.stones_.Add();
}
inline ::connect6::Point* Move::add_stones() {
  ::connect6::Point* _add = _internal_add_stones();
  // @@protoc_insertion_point(field_add:connect6.Move.stones)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >&
Move::stones() const {
  // @@protoc_insertion_point(field_list:connect6.Move.stones)
  return _impl_.stones_;
}

// -------------------------------------------------------------------

// Row

// repeated .connect6.PlayerColor cells = 1;
inline int Row::_internal_cells_size() const {
  return _impl_.cells_.size();
}
inline int Row::cells_size() const {
  return _internal_cells_size();
}
inline void Row::clear_cells() {
  _impl_.cells_.Clear();
}
inline ::connect6::PlayerColor Row::_internal_cells(int index) const {
  return static_cast< ::connect6::PlayerColor >(_impl_.cells_.Get(index));
}
inline ::connect6::PlayerColor Row::cells(int index) const {
  // @@protoc_insertion_point(field_get:connect6.Row.cells)
  return _internal_cells(index);
}
inline void Row::set_cells(int index, ::connect6::PlayerColor value) {
  _impl_.cells_.Set(index, value);
  // @@protoc_insertion_point(field_set:connect6.Row.cells)
}
inline void Row::_internal_add_cells(::connect6::PlayerColor value) {
  _impl_.cells_.Add(value);
}
inline void Row::add_cells(::connect6::PlayerColor value) {
  _internal_add_cells(value);
  // @@protoc_insertion_point(field_add:connect6.Row.cells)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
Row::cells() const {
  // @@protoc_insertion_point(field_list:connect6.Row.cells)
  return _impl_.cells_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Row::_internal_mutable_cells() {
  return &_impl_.cells_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
Row::mutable_cells() {
  // @@protoc_insertion_point(field_mutable_list:connect6.Row.cells)
  return _internal_mutable_cells();
}

// -------------------------------------------------------------------

// GameState

// .connect6.GameState.Status status = 1;
inline void GameState::clear_status() {
  _impl_.status_ = 0;
}
inline ::connect6::GameState_Status GameState::_internal_status() const {
  return static_cast< ::connect6::GameState_Status >(_impl_.status_);
}
inline ::connect6::GameState_Status GameState::status() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.status)
  return _internal_status();
}
inline void GameState::_internal_set_status(::connect6::GameState_Status value) {
  
  _impl_.status_ = value;
}
inline void GameState::set_status(::connect6::GameState_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.status)
}

// bool is_my_turn = 2;
inline void GameState::clear_is_my_turn() {
  _impl_.is_my_turn_ = false;
}
inline bool GameState::_internal_is_my_turn() const {
  return _impl_.is_my_turn_;
}
inline bool GameState::is_my_turn() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.is_my_turn)
  return _internal_is_my_turn();
}
inline void GameState::_internal_set_is_my_turn(bool value) {
  
  _impl_.is_my_turn_ = value;
}
inline void GameState::set_is_my_turn(bool value) {
  _internal_set_is_my_turn(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.is_my_turn)
}

// .connect6.PlayerColor my_color = 3;
inline void GameState::clear_my_color() {
  _impl_.my_color_ = 0;
}
inline ::connect6::PlayerColor GameState::_internal_my_color() const {
  return static_cast< ::connect6::PlayerColor >(_impl_.my_color_);
}
inline ::connect6::PlayerColor GameState::my_color() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.my_color)
  return _internal_my_color();
}
inline void GameState::_internal_set_my_color(::connect6::PlayerColor value) {
  
  _impl_.my_color_ = value;
}
inline void GameState::set_my_color(::connect6::PlayerColor value) {
  _internal_set_my_color(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.my_color)
}

// repeated .connect6.Point opponent_stones = 4;
inline int GameState::_internal_opponent_stones_size() const {
  return _impl_.opponent_stones_.size();
}
inline int GameState::opponent_stones_size() const {
  return _internal_opponent_stones_size();
}
inline void GameState::clear_opponent_stones() {
  _impl_.opponent_stones_.Clear();
}
inline ::connect6::Point* GameState::mutable_opponent_stones(int index) {
  // @@protoc_insertion_point(field_mutable:connect6.GameState.opponent_stones)
  return _impl_.opponent_stones_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >*
GameState::mutable_opponent_stones() {
  // @@protoc_insertion_point(field_mutable_list:connect6.GameState.opponent_stones)
  return &_impl_.opponent_stones_;
}
inline const ::connect6::Point& GameState::_internal_opponent_stones(int index) const {
  return _impl_.opponent_stones_.Get(index);
}
inline const ::connect6::Point& GameState::opponent_stones(int index) const {
  // @@protoc_insertion_point(field_get:connect6.GameState.opponent_stones)
  return _internal_opponent_stones(index);
}
inline ::connect6::Point* GameState::_internal_add_opponent_stones() {
  return _impl_.opponent_stones_.Add();
}
inline ::connect6::Point* GameState::add_opponent_stones() {
  ::connect6::Point* _add = _internal_add_opponent_stones();
  // @@protoc_insertion_point(field_add:connect6.GameState.opponent_stones)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Point >&
GameState::opponent_stones() const {
  // @@protoc_insertion_point(field_list:connect6.GameState.opponent_stones)
  return _impl_.opponent_stones_;
}

// int32 stones_required = 5;
inline void GameState::clear_stones_required() {
  _impl_.stones_required_ = 0;
}
inline int32_t GameState::_internal_stones_required() const {
  return _impl_.stones_required_;
}
inline int32_t GameState::stones_required() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.stones_required)
  return _internal_stones_required();
}
inline void GameState::_internal_set_stones_required(int32_t value) {
  
  _impl_.stones_required_ = value;
}
inline void GameState::set_stones_required(int32_t value) {
  _internal_set_stones_required(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.stones_required)
}

// string message = 6;
inline void GameState::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& GameState::message() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GameState::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:connect6.GameState.message)
}
inline std::string* GameState::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:connect6.GameState.message)
  return _s;
}
inline const std::string& GameState::_internal_message() const {
  return _impl_.message_.Get();
}
inline void GameState::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* GameState::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* GameState::release_message() {
  // @@protoc_insertion_point(field_release:connect6.GameState.message)
  return _impl_.message_.Release();
}
inline void GameState::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:connect6.GameState.message)
}

// .connect6.PlayerColor winner = 7;
inline void GameState::clear_winner() {
  _impl_.winner_ = 0;
}
inline ::connect6::PlayerColor GameState::_internal_winner() const {
  return static_cast< ::connect6::PlayerColor >(_impl_.winner_);
}
inline ::connect6::PlayerColor GameState::winner() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.winner)
  return _internal_winner();
}
inline void GameState::_internal_set_winner(::connect6::PlayerColor value) {
  
  _impl_.winner_ = value;
}
inline void GameState::set_winner(::connect6::PlayerColor value) {
  _internal_set_winner(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.winner)
}

// .connect6.GameResult result = 8;
inline void GameState::clear_result() {
  _impl_.result_ = 0;
}
inline ::connect6::GameResult GameState::_internal_result() const {
  return static_cast< ::connect6::GameResult >(_impl_.result_);
}
inline ::connect6::GameResult GameState::result() const {
  // @@protoc_insertion_point(field_get:connect6.GameState.result)
  return _internal_result();
}
inline void GameState::_internal_set_result(::connect6::GameResult value) {
  
  _impl_.result_ = value;
}
inline void GameState::set_result(::connect6::GameResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:connect6.GameState.result)
}

// repeated .connect6.Row board = 9;
inline int GameState::_internal_board_size() const {
  return _impl_.board_.size();
}
inline int GameState::board_size() const {
  return _internal_board_size();
}
inline void GameState::clear_board() {
  _impl_.board_.Clear();
}
inline ::connect6::Row* GameState::mutable_board(int index) {
  // @@protoc_insertion_point(field_mutable:connect6.GameState.board)
  return _impl_.board_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Row >*
GameState::mutable_board() {
  // @@protoc_insertion_point(field_mutable_list:connect6.GameState.board)
  return &_impl_.board_;
}
inline const ::connect6::Row& GameState::_internal_board(int index) const {
  return _impl_.board_.Get(index);
}
inline const ::connect6::Row& GameState::board(int index) const {
  // @@protoc_insertion_point(field_get:connect6.GameState.board)
  return _internal_board(index);
}
inline ::connect6::Row* GameState::_internal_add_board() {
  return _impl_.board_.Add();
}
inline ::connect6::Row* GameState::add_board() {
  ::connect6::Row* _add = _internal_add_board();
  // @@protoc_insertion_point(field_add:connect6.GameState.board)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::connect6::Row >&
GameState::board() const {
  // @@protoc_insertion_point(field_list:connect6.GameState.board)
  return _impl_.board_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace connect6

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::connect6::GameState_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::connect6::GameState_Status>() {
  return ::connect6::GameState_Status_descriptor();
}
template <> struct is_proto_enum< ::connect6::PlayerColor> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::connect6::PlayerColor>() {
  return ::connect6::PlayerColor_descriptor();
}
template <> struct is_proto_enum< ::connect6::GameResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::connect6::GameResult>() {
  return ::connect6::GameResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_connect6_2eproto
