services:
  servidor:
    image: lrprll/connect6-server:latest
    ports:
      - "8080:8080"
    networks:
      - game-network

  ia-main:
    build: ./AI_MiniMax_VCF_Zobrist
    restart: always
    environment:
      - SERVER_ADDR=servidor:50051
      - TEAM_NAME=Bot_Jorge
    depends_on:
      - servidor
    networks:
      - game-network

networks:
  game-network:
    driver: bridge