services:
  servidor:
    image: lrprll/connect6-server:latest
    ports:
      - "8080:8080"
    networks:
      - game-network

  ia-main:
    build: ./agente_cpp_worse_vcf
    restart: always
    environment:
      - SERVER_ADDR=servidor:50051
      - TEAM_NAME=Bot_CPP_Worse_VCF
    depends_on:
      - servidor
    networks:
      - game-network

  ia-worse:
    build: ./agente_cpp_worse
    restart: always
    environment:
      - SERVER_ADDR=servidor:50051
      - TEAM_NAME=Bot_CPP_Worse
    depends_on:
      - servidor
    networks:
      - game-network

networks:
  game-network:
    driver: bridge