// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: connect6.proto

#include "connect6.pb.h"
#include "connect6.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace connect6 {

static const char* GameServer_method_names[] = {
  "/connect6.GameServer/Play",
};

std::unique_ptr< GameServer::Stub> GameServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GameServer::Stub> stub(new GameServer::Stub(channel, options));
  return stub;
}

GameServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Play_(GameServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::connect6::PlayerAction, ::connect6::GameState>* GameServer::Stub::PlayRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::connect6::PlayerAction, ::connect6::GameState>::Create(channel_.get(), rpcmethod_Play_, context);
}

void GameServer::Stub::async::Play(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::connect6::PlayerAction,::connect6::GameState>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::connect6::PlayerAction,::connect6::GameState>::Create(stub_->channel_.get(), stub_->rpcmethod_Play_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::connect6::PlayerAction, ::connect6::GameState>* GameServer::Stub::AsyncPlayRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::connect6::PlayerAction, ::connect6::GameState>::Create(channel_.get(), cq, rpcmethod_Play_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::connect6::PlayerAction, ::connect6::GameState>* GameServer::Stub::PrepareAsyncPlayRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::connect6::PlayerAction, ::connect6::GameState>::Create(channel_.get(), cq, rpcmethod_Play_, context, false, nullptr);
}

GameServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GameServer_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< GameServer::Service, ::connect6::PlayerAction, ::connect6::GameState>(
          [](GameServer::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::connect6::GameState,
             ::connect6::PlayerAction>* stream) {
               return service->Play(ctx, stream);
             }, this)));
}

GameServer::Service::~Service() {
}

::grpc::Status GameServer::Service::Play(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::connect6::GameState, ::connect6::PlayerAction>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace connect6

