// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: connect6.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerColor int32

const (
	PlayerColor_UNKNOWN PlayerColor = 0
	PlayerColor_BLACK   PlayerColor = 1
	PlayerColor_WHITE   PlayerColor = 2
)

// Enum value maps for PlayerColor.
var (
	PlayerColor_name = map[int32]string{
		0: "UNKNOWN",
		1: "BLACK",
		2: "WHITE",
	}
	PlayerColor_value = map[string]int32{
		"UNKNOWN": 0,
		"BLACK":   1,
		"WHITE":   2,
	}
)

func (x PlayerColor) Enum() *PlayerColor {
	p := new(PlayerColor)
	*p = x
	return p
}

func (x PlayerColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerColor) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[0].Descriptor()
}

func (PlayerColor) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[0]
}

func (x PlayerColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerColor.Descriptor instead.
func (PlayerColor) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{0}
}

type GameResult int32

const (
	GameResult_ONGOING       GameResult = 0
	GameResult_BLACK_WIN     GameResult = 1
	GameResult_WHITE_WIN     GameResult = 2
	GameResult_DRAW          GameResult = 3
	GameResult_BLACK_TIMEOUT GameResult = 4
	GameResult_WHITE_TIMEOUT GameResult = 5
	GameResult_BLACK_INVALID GameResult = 6
	GameResult_WHITE_INVALID GameResult = 7
)

// Enum value maps for GameResult.
var (
	GameResult_name = map[int32]string{
		0: "ONGOING",
		1: "BLACK_WIN",
		2: "WHITE_WIN",
		3: "DRAW",
		4: "BLACK_TIMEOUT",
		5: "WHITE_TIMEOUT",
		6: "BLACK_INVALID",
		7: "WHITE_INVALID",
	}
	GameResult_value = map[string]int32{
		"ONGOING":       0,
		"BLACK_WIN":     1,
		"WHITE_WIN":     2,
		"DRAW":          3,
		"BLACK_TIMEOUT": 4,
		"WHITE_TIMEOUT": 5,
		"BLACK_INVALID": 6,
		"WHITE_INVALID": 7,
	}
)

func (x GameResult) Enum() *GameResult {
	p := new(GameResult)
	*p = x
	return p
}

func (x GameResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResult) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[1].Descriptor()
}

func (GameResult) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[1]
}

func (x GameResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResult.Descriptor instead.
func (GameResult) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{1}
}

type GameState_Status int32

const (
	GameState_WAITING  GameState_Status = 0
	GameState_PLAYING  GameState_Status = 1
	GameState_FINISHED GameState_Status = 2
)

// Enum value maps for GameState_Status.
var (
	GameState_Status_name = map[int32]string{
		0: "WAITING",
		1: "PLAYING",
		2: "FINISHED",
	}
	GameState_Status_value = map[string]int32{
		"WAITING":  0,
		"PLAYING":  1,
		"FINISHED": 2,
	}
)

func (x GameState_Status) Enum() *GameState_Status {
	p := new(GameState_Status)
	*p = x
	return p
}

func (x GameState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_connect6_proto_enumTypes[2].Descriptor()
}

func (GameState_Status) Type() protoreflect.EnumType {
	return &file_connect6_proto_enumTypes[2]
}

func (x GameState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState_Status.Descriptor instead.
func (GameState_Status) EnumDescriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{4, 0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_connect6_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*PlayerAction_RegisterTeam
	//	*PlayerAction_Move
	//	*PlayerAction_Resign
	Action        isPlayerAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_connect6_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAction) GetAction() isPlayerAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PlayerAction) GetRegisterTeam() string {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_RegisterTeam); ok {
			return x.RegisterTeam
		}
	}
	return ""
}

func (x *PlayerAction) GetMove() *Move {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *PlayerAction) GetResign() bool {
	if x != nil {
		if x, ok := x.Action.(*PlayerAction_Resign); ok {
			return x.Resign
		}
	}
	return false
}

type isPlayerAction_Action interface {
	isPlayerAction_Action()
}

type PlayerAction_RegisterTeam struct {
	RegisterTeam string `protobuf:"bytes,1,opt,name=register_team,json=registerTeam,proto3,oneof"`
}

type PlayerAction_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type PlayerAction_Resign struct {
	Resign bool `protobuf:"varint,3,opt,name=resign,proto3,oneof"`
}

func (*PlayerAction_RegisterTeam) isPlayerAction_Action() {}

func (*PlayerAction_Move) isPlayerAction_Action() {}

func (*PlayerAction_Resign) isPlayerAction_Action() {}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stones        []*Point               `protobuf:"bytes,1,rep,name=stones,proto3" json:"stones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_connect6_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{2}
}

func (x *Move) GetStones() []*Point {
	if x != nil {
		return x.Stones
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []PlayerColor          `protobuf:"varint,1,rep,packed,name=cells,proto3,enum=connect6.PlayerColor" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_connect6_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetCells() []PlayerColor {
	if x != nil {
		return x.Cells
	}
	return nil
}

type GameState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         GameState_Status       `protobuf:"varint,1,opt,name=status,proto3,enum=connect6.GameState_Status" json:"status,omitempty"`
	IsMyTurn       bool                   `protobuf:"varint,2,opt,name=is_my_turn,json=isMyTurn,proto3" json:"is_my_turn,omitempty"`
	MyColor        PlayerColor            `protobuf:"varint,3,opt,name=my_color,json=myColor,proto3,enum=connect6.PlayerColor" json:"my_color,omitempty"`
	OpponentStones []*Point               `protobuf:"bytes,4,rep,name=opponent_stones,json=opponentStones,proto3" json:"opponent_stones,omitempty"`
	StonesRequired int32                  `protobuf:"varint,5,opt,name=stones_required,json=stonesRequired,proto3" json:"stones_required,omitempty"` // <--- NUEVO
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Winner         PlayerColor            `protobuf:"varint,7,opt,name=winner,proto3,enum=connect6.PlayerColor" json:"winner,omitempty"`
	Result         GameResult             `protobuf:"varint,8,opt,name=result,proto3,enum=connect6.GameResult" json:"result,omitempty"`
	Board          []*Row                 `protobuf:"bytes,9,rep,name=board,proto3" json:"board,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_connect6_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_connect6_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_connect6_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetStatus() GameState_Status {
	if x != nil {
		return x.Status
	}
	return GameState_WAITING
}

func (x *GameState) GetIsMyTurn() bool {
	if x != nil {
		return x.IsMyTurn
	}
	return false
}

func (x *GameState) GetMyColor() PlayerColor {
	if x != nil {
		return x.MyColor
	}
	return PlayerColor_UNKNOWN
}

func (x *GameState) GetOpponentStones() []*Point {
	if x != nil {
		return x.OpponentStones
	}
	return nil
}

func (x *GameState) GetStonesRequired() int32 {
	if x != nil {
		return x.StonesRequired
	}
	return 0
}

func (x *GameState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameState) GetWinner() PlayerColor {
	if x != nil {
		return x.Winner
	}
	return PlayerColor_UNKNOWN
}

func (x *GameState) GetResult() GameResult {
	if x != nil {
		return x.Result
	}
	return GameResult_ONGOING
}

func (x *GameState) GetBoard() []*Row {
	if x != nil {
		return x.Board
	}
	return nil
}

var File_connect6_proto protoreflect.FileDescriptor

const file_connect6_proto_rawDesc = "" +
	"\n" +
	"\x0econnect6.proto\x12\bconnect6\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x7f\n" +
	"\fPlayerAction\x12%\n" +
	"\rregister_team\x18\x01 \x01(\tH\x00R\fregisterTeam\x12$\n" +
	"\x04move\x18\x02 \x01(\v2\x0e.connect6.MoveH\x00R\x04move\x12\x18\n" +
	"\x06resign\x18\x03 \x01(\bH\x00R\x06resignB\b\n" +
	"\x06action\"/\n" +
	"\x04Move\x12'\n" +
	"\x06stones\x18\x01 \x03(\v2\x0f.connect6.PointR\x06stones\"2\n" +
	"\x03Row\x12+\n" +
	"\x05cells\x18\x01 \x03(\x0e2\x15.connect6.PlayerColorR\x05cells\"\xc0\x03\n" +
	"\tGameState\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.connect6.GameState.StatusR\x06status\x12\x1c\n" +
	"\n" +
	"is_my_turn\x18\x02 \x01(\bR\bisMyTurn\x120\n" +
	"\bmy_color\x18\x03 \x01(\x0e2\x15.connect6.PlayerColorR\amyColor\x128\n" +
	"\x0fopponent_stones\x18\x04 \x03(\v2\x0f.connect6.PointR\x0eopponentStones\x12'\n" +
	"\x0fstones_required\x18\x05 \x01(\x05R\x0estonesRequired\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12-\n" +
	"\x06winner\x18\a \x01(\x0e2\x15.connect6.PlayerColorR\x06winner\x12,\n" +
	"\x06result\x18\b \x01(\x0e2\x14.connect6.GameResultR\x06result\x12#\n" +
	"\x05board\x18\t \x03(\v2\r.connect6.RowR\x05board\"0\n" +
	"\x06Status\x12\v\n" +
	"\aWAITING\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02*0\n" +
	"\vPlayerColor\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05BLACK\x10\x01\x12\t\n" +
	"\x05WHITE\x10\x02*\x8d\x01\n" +
	"\n" +
	"GameResult\x12\v\n" +
	"\aONGOING\x10\x00\x12\r\n" +
	"\tBLACK_WIN\x10\x01\x12\r\n" +
	"\tWHITE_WIN\x10\x02\x12\b\n" +
	"\x04DRAW\x10\x03\x12\x11\n" +
	"\rBLACK_TIMEOUT\x10\x04\x12\x11\n" +
	"\rWHITE_TIMEOUT\x10\x05\x12\x11\n" +
	"\rBLACK_INVALID\x10\x06\x12\x11\n" +
	"\rWHITE_INVALID\x10\a2E\n" +
	"\n" +
	"GameServer\x127\n" +
	"\x04Play\x12\x16.connect6.PlayerAction\x1a\x13.connect6.GameState(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_connect6_proto_rawDescOnce sync.Once
	file_connect6_proto_rawDescData []byte
)

func file_connect6_proto_rawDescGZIP() []byte {
	file_connect6_proto_rawDescOnce.Do(func() {
		file_connect6_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect6_proto_rawDesc), len(file_connect6_proto_rawDesc)))
	})
	return file_connect6_proto_rawDescData
}

var file_connect6_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_connect6_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_connect6_proto_goTypes = []any{
	(PlayerColor)(0),      // 0: connect6.PlayerColor
	(GameResult)(0),       // 1: connect6.GameResult
	(GameState_Status)(0), // 2: connect6.GameState.Status
	(*Point)(nil),         // 3: connect6.Point
	(*PlayerAction)(nil),  // 4: connect6.PlayerAction
	(*Move)(nil),          // 5: connect6.Move
	(*Row)(nil),           // 6: connect6.Row
	(*GameState)(nil),     // 7: connect6.GameState
}
var file_connect6_proto_depIdxs = []int32{
	5,  // 0: connect6.PlayerAction.move:type_name -> connect6.Move
	3,  // 1: connect6.Move.stones:type_name -> connect6.Point
	0,  // 2: connect6.Row.cells:type_name -> connect6.PlayerColor
	2,  // 3: connect6.GameState.status:type_name -> connect6.GameState.Status
	0,  // 4: connect6.GameState.my_color:type_name -> connect6.PlayerColor
	3,  // 5: connect6.GameState.opponent_stones:type_name -> connect6.Point
	0,  // 6: connect6.GameState.winner:type_name -> connect6.PlayerColor
	1,  // 7: connect6.GameState.result:type_name -> connect6.GameResult
	6,  // 8: connect6.GameState.board:type_name -> connect6.Row
	4,  // 9: connect6.GameServer.Play:input_type -> connect6.PlayerAction
	7,  // 10: connect6.GameServer.Play:output_type -> connect6.GameState
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_connect6_proto_init() }
func file_connect6_proto_init() {
	if File_connect6_proto != nil {
		return
	}
	file_connect6_proto_msgTypes[1].OneofWrappers = []any{
		(*PlayerAction_RegisterTeam)(nil),
		(*PlayerAction_Move)(nil),
		(*PlayerAction_Resign)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect6_proto_rawDesc), len(file_connect6_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connect6_proto_goTypes,
		DependencyIndexes: file_connect6_proto_depIdxs,
		EnumInfos:         file_connect6_proto_enumTypes,
		MessageInfos:      file_connect6_proto_msgTypes,
	}.Build()
	File_connect6_proto = out.File
	file_connect6_proto_goTypes = nil
	file_connect6_proto_depIdxs = nil
}
