// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: connect6.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameServer_Play_FullMethodName = "/connect6.GameServer/Play"
)

// GameServerClient is the client API for GameServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServerClient interface {
	Play(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, GameState], error)
}

type gameServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServerClient(cc grpc.ClientConnInterface) GameServerClient {
	return &gameServerClient{cc}
}

func (c *gameServerClient) Play(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PlayerAction, GameState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameServer_ServiceDesc.Streams[0], GameServer_Play_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayerAction, GameState]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServer_PlayClient = grpc.BidiStreamingClient[PlayerAction, GameState]

// GameServerServer is the server API for GameServer service.
// All implementations must embed UnimplementedGameServerServer
// for forward compatibility.
type GameServerServer interface {
	Play(grpc.BidiStreamingServer[PlayerAction, GameState]) error
	mustEmbedUnimplementedGameServerServer()
}

// UnimplementedGameServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServerServer struct{}

func (UnimplementedGameServerServer) Play(grpc.BidiStreamingServer[PlayerAction, GameState]) error {
	return status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedGameServerServer) mustEmbedUnimplementedGameServerServer() {}
func (UnimplementedGameServerServer) testEmbeddedByValue()                    {}

// UnsafeGameServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServerServer will
// result in compilation errors.
type UnsafeGameServerServer interface {
	mustEmbedUnimplementedGameServerServer()
}

func RegisterGameServerServer(s grpc.ServiceRegistrar, srv GameServerServer) {
	// If the following call panics, it indicates UnimplementedGameServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameServer_ServiceDesc, srv)
}

func _GameServer_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServerServer).Play(&grpc.GenericServerStream[PlayerAction, GameState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameServer_PlayServer = grpc.BidiStreamingServer[PlayerAction, GameState]

// GameServer_ServiceDesc is the grpc.ServiceDesc for GameServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connect6.GameServer",
	HandlerType: (*GameServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Play",
			Handler:       _GameServer_Play_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connect6.proto",
}
